export type SimulationInput={missOffsetKm:number;speedKmS:number;directionDeg:number;uncertaintyKm:number;asteroidDiameterM:number;orbitBiasDeg:number};
export type SimulationResult={status:"clear"|"close"|"overlap";closestDistanceKm:number;safetyMarginKm:number;durationHours:number;points:{x:number;y:number;z:number}[]};
export const defaults:SimulationInput={missOffsetKm:34000,speedKmS:13.2,directionDeg:28,uncertaintyKm:1800,asteroidDiameterM:490,orbitBiasDeg:0};
export const presets=[{name:"Nearby pass",note:"A visible pass near Earth.",input:defaults},{name:"Wide pass",note:"More space between the paths.",input:{...defaults,missOffsetKm:56000,speedKmS:18.4,uncertaintyKm:900,directionDeg:42}},{name:"Uncertain path",note:"A wider range around the path.",input:{...defaults,missOffsetKm:12800,uncertaintyKm:6200,directionDeg:14}}];
const limit=(value:number,min:number,max:number)=>Math.min(Math.max(value,min),max);
export function calculate(input:SimulationInput):SimulationResult{const offset=limit(input.missOffsetKm,0,100000),speed=limit(input.speedKmS,1,80),uncertainty=limit(input.uncertaintyKm,0,25000),angle=(input.directionDeg+input.orbitBiasDeg)*Math.PI/180,closest=Math.round(offset*(.72+Math.abs(Math.cos(angle))*.28)),surface=Math.max(0,closest-6371-input.asteroidDiameterM/2000),margin=Math.round(surface-uncertainty),status=surface<=uncertainty?"overlap":margin<16000?"close":"clear",z=Math.sin(angle)*.65,visual=.12+closest/100000*6;return{status,closestDistanceKm:closest,safetyMarginKm:margin,durationHours:Number((180000/speed/3600).toFixed(1)),points:Array.from({length:25},(_,i)=>{const t=i/24;return{x:-9+t*18,y:visual+Math.sin(t*Math.PI)*z+(1-Math.pow((t-.5)*2,2))*.18,z:(t-.5)*.65}})}}
export const formatKm=(value:number)=>value>=1000?`${Math.round(value/1000)}k km`:`${Math.round(value)} km`;
export const resultText=(status:SimulationResult["status"])=>status==="overlap"?"The uncertainty range reaches Earth in this local model.":status==="close"?"The path remains clear, but the uncertainty range is close to Earth.":"The path and uncertainty range remain clear of Earth in this local model.";
export const visualMode=(reduced:boolean,webgl:boolean)=>!reduced&&webgl?"3d":"2d";
