import {useLandingMotion} from "@/components/LandingMotion";
import {useTheme} from "@/contexts/ThemeContext";
import {Moon,Sun} from "lucide-react";
import {useRef,useState} from "react";
import {Link} from "wouter";

const heroVideo="https://ruowk8tkywyw4yft.public.blob.vercel-storage.com/video/earth-rotating.mp4";
const poster="/manus-storage/gravexa-art-direction_61441308.png";

function Arrow(){return <svg viewBox="0 0 20 20" className="size-4 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" aria-hidden="true"><path d="M5 15 15 5M7 5h8v8" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Theme(){const{theme,toggleTheme}=useTheme();return <button onClick={toggleTheme} aria-label="Change color theme" className="grid size-8 place-items-center rounded-full bg-secondary transition-transform duration-200 hover:scale-105 active:scale-95">{theme==="dark"?<Sun size={14}/>:<Moon size={14}/>}</button>}

export default function Home(){const ref=useRef<HTMLElement>(null),[videoFailed,setVideoFailed]=useState(false);useLandingMotion(ref);return <main ref={ref} className="space-grain min-h-[100dvh] overflow-hidden bg-background"><header className="fixed inset-x-0 top-0 z-30 px-4 pt-4 sm:px-6 sm:pt-6"><nav aria-label="Primary navigation" className="mx-auto flex max-w-5xl items-center justify-between rounded-full border border-white/15 bg-[#071027]/70 px-4 py-3 text-[#eef4ff] shadow-[0_12px_32px_rgba(0,0,0,.26)] backdrop-blur-xl"><a href="#top" className="font-data text-xs tracking-[.15em]">GRAVEXA</a><div className="hidden gap-5 text-xs font-semibold text-[#b9c8e7] sm:flex"><a href="#how" className="hover:text-white">How it works</a><a href="#limits" className="hover:text-white">Model limits</a></div><div className="flex gap-2"><Theme/><Link href="/simulator" className="group inline-flex items-center gap-2 rounded-full bg-white py-1.5 pl-3 pr-1.5 text-xs font-bold text-[#10182c]"><span>Open simulator</span><span className="grid size-6 place-items-center rounded-full bg-[#10182c] text-white"><Arrow/></span></Link></div></nav></header>

<section id="top" className="relative flex min-h-[100dvh] items-end overflow-hidden px-4 pb-8 pt-28 sm:px-6 sm:pb-12 lg:px-10">
  <img src={poster} alt="" aria-hidden="true" className={`absolute inset-0 size-full object-cover object-center ${videoFailed?"":"motion-safe:hidden"}`}/>
  {!videoFailed&&<video autoPlay muted loop playsInline preload="metadata" poster={poster} aria-hidden="true" onError={()=>setVideoFailed(true)} className="absolute inset-0 size-full object-cover object-center motion-reduce:hidden"><source src={heroVideo} type="video/mp4"/></video>}
  <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,7,18,.96),rgba(3,7,18,.72)_42%,rgba(3,7,18,.3)_76%,rgba(3,7,18,.72))]"/>
  <div className="absolute inset-0 bg-[radial-gradient(circle_at_58%_50%,transparent_0,rgba(3,7,18,.26)_47%,rgba(3,7,18,.82)_100%)]"/>
  <svg viewBox="0 0 760 430" className="pointer-events-none absolute inset-0 size-full" aria-hidden="true"><path d="M-80 104C166 21 342 86 477 198S726 345 848 268" fill="none" stroke="#9c8ef5" strokeOpacity=".16" strokeWidth="64"/><path d="M-80 104C166 21 342 86 477 198S726 345 848 268" fill="none" stroke="#d7e4ff" strokeOpacity=".85" strokeWidth="2" strokeDasharray="9 10"/><circle cx="477" cy="198" r="35" fill="#61a7ff" fillOpacity=".18"/><circle cx="477" cy="198" r="24" fill="#2765c2" stroke="#b9e2ff"/><circle cx="346" cy="87" r="6" fill="#f6bf67"/><path d="M346 76V44H476" fill="none" stroke="#c9d8fb" strokeOpacity=".5"/><text x="484" y="48" fill="#d7e4ff" fontSize="11" fontFamily="Fragment Mono,monospace">CLOSEST POINT</text></svg>
  <div className="relative mx-auto grid w-full max-w-[1400px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div className="max-w-2xl pb-4"><p data-hero className="font-data text-[10px] tracking-[.17em] text-[#c6d7fb]">AN INTERACTIVE SPACE-LEARNING TOOL</p><h1 data-hero className="mt-5 text-balance text-5xl font-semibold leading-[.97] tracking-[-.065em] text-white sm:text-7xl lg:text-[5.4rem]">What changes when an asteroid passes Earth?</h1><p data-hero className="mt-6 max-w-lg text-base leading-7 text-[#d0ddf7] sm:text-lg">Move a few values. Watch the path change. Learn what a close approach means in a clear, visual way.</p><div data-hero className="mt-8 flex flex-wrap gap-3"><Link href="/simulator" className="group inline-flex items-center gap-3 rounded-full bg-white py-2 pl-5 pr-2 text-sm font-bold text-[#10182c] transition-transform duration-200 hover:scale-[1.02] active:scale-95">Try the simulator<span className="grid size-8 place-items-center rounded-full bg-[#10182c] text-white"><Arrow/></span></Link><a href="#how" className="rounded-full border border-white/20 bg-[#071027]/40 px-5 py-2 text-sm font-semibold text-white backdrop-blur-sm">See how it works</a></div></div><div data-hero className="justify-self-end rounded-[1.7rem] border border-white/15 bg-[#071027]/66 p-5 text-[#e8efff] shadow-[0_20px_60px_rgba(0,0,0,.24)] backdrop-blur-xl sm:w-[340px]"><p className="font-data text-[10px] tracking-[.15em] text-[#a6badf]">START WITH A LOCAL MODEL</p><p className="mt-4 text-lg font-semibold">Change one thing at a time.</p><p className="mt-2 text-sm leading-6 text-[#c3d1eb]">Gravexa shows a simple model. It does not predict a real collision.</p><div className="mt-5 flex justify-between border-t border-white/10 pt-4 font-data text-[10px] tracking-[.1em] text-[#a6badf]"><span>NO SAVED DATA</span><span>FREE TO EXPLORE</span></div></div></div>
</section>

<section id="how" className="mx-auto max-w-5xl px-4 py-24 sm:px-6 sm:py-36" style={{contentVisibility:"auto",containIntrinsicSize:"auto 760px"}}><div data-reveal><p className="font-data text-[10px] tracking-[.16em] text-muted-foreground">A SIMPLE PATH, MADE VISIBLE</p><h2 className="mt-4 max-w-3xl text-balance text-3xl font-semibold tracking-[-.05em] sm:text-5xl">The important idea is distance, not drama.</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3" data-reveal>{[["01","Choose a path","Set how far the asteroid path sits from Earth and its direction across the view."],["02","Add uncertainty","Widen the path range to see why a single line cannot tell the whole story."],["03","Read the result","See the closest point and a plain-language result from the same local values."]].map(([step,title,text])=><article key={step} className="bg-card p-7 sm:p-8"><span className="font-data text-xs text-primary">{step}</span><h3 className="mt-10 text-xl font-semibold tracking-[-.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section>
<section className="border-y border-border bg-secondary/40" style={{contentVisibility:"auto",containIntrinsicSize:"auto 720px"}}><div className="mx-auto grid max-w-5xl gap-12 px-4 py-24 sm:px-6 sm:py-32 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div data-reveal><p className="font-data text-[10px] tracking-[.16em] text-muted-foreground">BUILT FOR LEARNING</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-.05em] sm:text-5xl">Learn the words by changing the picture.</h2></div><div data-reveal className="space-y-7">{[["Closest approach","This is the smallest gap between the shown asteroid path and Earth."],["Uncertainty range","This is the wider space around the shown path. A wider range gives less certainty."],["Local model","This calculation runs in your browser. It uses fewer inputs than real mission work."]].map(([title,text])=><div key={title} className="border-b border-border pb-7 last:border-0"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
<section id="limits" className="mx-auto max-w-5xl px-4 py-24 sm:px-6 sm:py-36" style={{contentVisibility:"auto",containIntrinsicSize:"auto 560px"}}><div data-reveal className="rounded-[2rem] border border-border bg-card p-7 shadow-[0_20px_50px_rgba(0,0,0,.16)] sm:p-10"><p className="font-data text-[10px] tracking-[.16em] text-muted-foreground">KEEP THE DIFFERENCE CLEAR</p><div className="mt-5 grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><h2 className="text-balance text-3xl font-semibold tracking-[-.05em] sm:text-5xl">Gravexa is a learning model. NASA and JPL data are reference information.</h2><p className="mt-5 max-w-2xl text-sm leading-6 text-muted-foreground">The simulator makes a local result from your values. A separate panel can show real object data from JPL, but it does not change the local result.</p></div><Link href="/simulator" className="group inline-flex w-fit items-center gap-3 rounded-full bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground">Explore the model<span className="grid size-7 place-items-center rounded-full bg-primary-foreground text-primary"><Arrow/></span></Link></div></div></section>
<footer className="mx-auto flex max-w-5xl flex-col justify-between gap-5 border-t border-border px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:px-6"><p>Gravexa is a student project for learning about close approaches.</p><div className="flex gap-4"><a href="https://science.nasa.gov/resource/bennu-3d-model/" target="_blank" rel="noreferrer">NASA asset source</a><a href="https://ssd-api.jpl.nasa.gov/" target="_blank" rel="noreferrer">JPL reference data</a></div></footer></main>}
