import {z} from "zod";

export const explanationInput=z.object({status:z.enum(["clear","close","overlap"]),closestDistanceKm:z.number().finite().min(0).max(1000000),safetyMarginKm:z.number().finite().min(-1000000).max(1000000),speedKmS:z.number().finite().min(1).max(100),uncertaintyKm:z.number().finite().min(0).max(100000),asteroidDiameterM:z.number().finite().min(1).max(10000)});
export type ExplanationInput=z.infer<typeof explanationInput>;
export const explanationOutput=z.object({title:z.string().min(3).max(80),summary:z.string().min(10).max(420),whatChanged:z.string().min(10).max(420),note:z.string().min(10).max(260)});

export async function explainResult(input:ExplanationInput){const key=process.env.GROQ_API_KEY;if(!key)throw new Error("The Groq API key is not available.");const response=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.3-70b-versatile",temperature:.25,response_format:{type:"json_object"},messages:[{role:"system",content:"You explain one educational asteroid close-approach result. Use plain English. Do not claim that this is a real prediction. Return JSON only with title, summary, whatChanged, and note."},{role:"user",content:JSON.stringify(input)}]})});if(!response.ok)throw new Error("The explanation request did not complete.");const body=await response.json() as {choices?:{message?:{content?:string}}[]};const content=body.choices?.[0]?.message?.content;if(!content)throw new Error("The explanation service returned no text.");return explanationOutput.parse(JSON.parse(content));}

export const referenceInput=z.object({query:z.string().trim().min(2).max(60).regex(/^[a-zA-Z0-9 .()_-]+$/)});
export async function findReference(query:string){const url=new URL("https://ssd-api.jpl.nasa.gov/sbdb.api");url.searchParams.set("sstr",query);url.searchParams.set("full-prec","false");const response=await fetch(url,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error("The JPL reference request did not complete.");const body=await response.json() as {object?:{fullname?:string;des?:string};orbit?:{orbit_class?:{name?:string};elements?:{name?:string;value?:string}[]};signature?:{source?:string;version?:string}};return {name:body.object?.fullname??query,designation:body.object?.des??"Not available",classification:body.orbit?.orbit_class?.name??"Not available",elements:(body.orbit?.elements??[]).slice(0,5).map(item=>({name:item.name??"Value",value:item.value??"Not available"})),source:body.signature?.source??"NASA JPL Small-Body Database",version:body.signature?.version??""};}
